rhino animation fix
EMM-Gruppe8/Morphy pull request #50
Opened 2021-07-02 18:23 UTC by maginkaaa

2021-07-02 20:21 UTC, enze-l commented
Bei mir ist das rhino immer noch nicht annimiert wenn ich es übernehme.

2021-07-04 21:56 UTC, cmsk1 commented
Ich habe das auch grade mal probiert, das Rhino als Gegner ist nun animiert, als Spieler aber nicht. Ich musste für den Charakterwechsel ja die Animationen in den Resources Ordner kopieren, sodass es alle Animationen zwei Mal gibt. Vielleicht hilft es, die neue Animation vom Rhino in den Animation Order unter Resources zu kopieren. Ich habe es leider noch nicht geschafft, dass man nur einen Ordner hat.

2021-07-04 22:36 UTC, enze-l commented
Probiere es gerne mal aus. Ich hatte Magdalena das selbe geraten, allerdings schien es nicht zu helfen

2021-07-05 22:15 UTC, cmsk1 commented
> Probiere es gerne mal aus. Ich hatte Magdalena das selbe geraten, allerdings schien es nicht zu helfen

Ich habe auch grade probiert, leider auch ohne Erfolg. Keine Ahnung woran das liegen könnte. Zumindest die Enemy Rhinos haben aber ja nun eine Animation.

2021-07-07 13:33 UTC, enze-l requested changes
The Rhino still doesn't sprint

2021-07-25 14:25 UTC, closed without merging